apiVersion: v1
kind: Pod
metadata:
  name: env-test-pod
  labels:
    app: env-test
spec:
    containers:
    - name: env-test-container
      image: itselavia/dynamic-update-env
      envFrom:
      - configMapRef:
        name: env-vars
      volumeMounts:
      - mountPath: /config
        name: env-volume
    volumes:
    - name: env-volume
      configMap:
        name: env-vars