apiVersion: v1
kind: Pod
metadata:
  name: env-test-pod
spec:
  containers:
    - name: env-test-container
      image: k8s.gcr.io/busybox
      envFrom:
      - configMapRef:
          name: env-vars