apiVersion: v1
kind: Pod
metadata:
  name: env-test-pod
spec:
  containers:
    - name: env-test-container
      image: itselavia/dynamic-update-env
      envFrom:
      - configMapRef:
          name: env-vars